name: Test Coverage
on:
  pull_request: {branches: [main]}
jobs:
  Coverage:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install covr
        run: if (!require("covr")) install.packages("covr")
        shell: Rscript {0}
      - name: Run coverage
        run: covr::package_coverage(quiet = FALSE)
        shell: Rscript {0}

      # Add this
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
