name: Test Coverage

on:
  pull_request: {branches: [main]}

jobs:
  Coverage:
    runs-on: ubuntu-latest
    container: {image: "rocker/tidyverse:4.2.1"}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install covr
        run: if (!require("covr")) install.packages("covr")
        shell: Rscript {0}

      - name: Run coverage
        run: covr::package_coverage(quiet = FALSE, type = "all", clean = FALSE)
        shell: Rscript {0}

      - name: Convert to Cobertura XML
        run: covr::cobertura("coverage.xml", quiet = FALSE)
        shell: Rscript {0}

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
        with:
          coverage_file: "coverage.xml"  # Set the correct path
